name: "JFrog OIDC CI Workflow with Curation + Xray (Docker)"

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION || '3.11' }}
  BUILD_NAME:     ${{ vars.BUILD_NAME     || 'jfrog-docker-security-scan-build' }}
  BUILD_NUMBER:   ${{ vars.BUILD_NUMBER   || github.run_id }}
  # Artifactory
  DOCKER_REPO:    ${{ vars.DOCKER_REPO    || 'notes-api-docker-repo' }}
  JF_REGISTRY:    ${{ vars.JF_REGISTRY    || 'aboavent.jfrog.io' }}   # host only
  CURATED_PYPI_VIRTUAL: ${{ vars.CURATED_PYPI_VIRTUAL || 'pypi-curated' }}
  # Xray behavior
  FAIL_ON_SEVERITY: ${{ vars.FAIL_ON_SEVERITY || 'none' }}             # none|low|medium|high|critical
  XRAY_FORMAT: table
  # Quiet the CLI
  JFROG_CLI_LOG_LEVEL: ERROR
  JFROG_CLI_ENV_EXCLUDE: "*password*;*secret*;*key*;*token*;*auth*;JF_ARTIFACTORY_*;JF_ENV_*;JF_URL;JF_USER;JF_PASSWORD;JF_ACCESS_TOKEN"
  JFROG_CLI_OFFER_CONFIG: "false"

jobs:
  build-scan-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI (OIDC)
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}                        # e.g. https://aboavent.jfrog.io
        with:
          oidc-provider-name: github-oidc-integration

      - name: Ensure jq is available
        shell: bash
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y jq
          fi

      - name: "Sanity: show effective settings"
        shell: bash
        run: |
          set -euo pipefail
          echo "DOCKER_REPO=${{ env.DOCKER_REPO }}"
          jf rt curl -s -XGET "/api/repositories/${{ env.DOCKER_REPO }}" | jq '{key,packageType,type,repositories,defaultDeploymentRepo}' || true
          {
            echo "### JFrog Settings"
            echo "- **JF_URL**: \`${{ vars.JF_URL }}\`"
            echo "- **DOCKER_REPO**: \`${{ env.DOCKER_REPO }}\`"
            echo "- **JF_REGISTRY**: \`${{ env.JF_REGISTRY }}\`"
            echo "- **CURATED_PYPI_VIRTUAL**: \`${{ env.CURATED_PYPI_VIRTUAL }}\`"
          } >> "$GITHUB_STEP_SUMMARY"

      # ---------- Curation ----------
      - name: Configure pip (JFrog)
        shell: bash
        run: |
          jf pip c \
            --global \
            --server-id-resolve setup-jfrog-cli-server \
            --repo-resolve "${{ env.CURATED_PYPI_VIRTUAL }}"

      - name: Curation audit (requirements.txt)
        shell: bash
        run: jf curation-audit --requirements-file requirements.txt --format table || true

      # ---------- Source scan (non-blocking) ----------
      - name: Scan repository (non-blocking)
        shell: bash
        run: jf scan . --fail=false --format "${{ env.XRAY_FORMAT }}"

      # ---------- Build Docker image ----------
      - name: Compose image tag
        id: tags
        shell: bash
        run: |
          NAME="notes-api"
          SAFE_BRANCH=$(echo "${GITHUB_REF_NAME:-main}" | tr '/ ' '--')
          REF_TAG="${{ env.JF_REGISTRY }}/${{ env.DOCKER_REPO }}/${NAME}:${SAFE_BRANCH}"
          echo "ref_tag=${REF_TAG}" >> "$GITHUB_OUTPUT"

      - name: Build image (local)
        shell: bash
        run: |
          docker build -t "${{ steps.tags.outputs.ref_tag }}" .

      # ---------- Local image scan (Xray) ----------
      - name: Image scan (Xray, local daemon)
        shell: bash
        run: jf docker scan "${{ steps.tags.outputs.ref_tag }}" --fail=false --format "${{ env.XRAY_FORMAT }}"

      # ---------- Push & record build-info ----------
      - name: Push image & record build-info (ref tag only)
        env:
          BUILD_NAME:   ${{ env.BUILD_NAME }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        shell: bash
        run: |
          jf rt docker-push "${{ steps.tags.outputs.ref_tag }}" "${{ env.DOCKER_REPO }}" \
            --build-name "${BUILD_NAME}" --build-number "${BUILD_NUMBER}"

      # ---------- Publish build-info ----------
      - name: Publish build-info
        env:
          BUILD_NAME:   ${{ env.BUILD_NAME }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        run: jf rt build-publish "${BUILD_NAME}" "${BUILD_NUMBER}"

      # ---------- Xray Build Scan (policy-gated) ----------
      - name: Scan published build (policy-gated)
        env:
          BUILD_NAME:       ${{ env.BUILD_NAME }}
          BUILD_NUMBER:     ${{ env.BUILD_NUMBER }}
          FAIL_ON_SEVERITY: ${{ env.FAIL_ON_SEVERITY }}
        shell: bash
        run: |
          if [ "${FAIL_ON_SEVERITY}" = "none" ]; then
            jf bs "${BUILD_NAME}" "${BUILD_NUMBER}" || true
          else
            jf bs "${BUILD_NAME}" "${BUILD_NUMBER}" --fail-on-severity "${FAIL_ON_SEVERITY}"
          fi

      - name: Summarize Xray build scan in job summary
        env:
          BUILD_NAME:   ${{ env.BUILD_NAME }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        shell: bash
        run: |
          set -euo pipefail
          jf bs "${BUILD_NAME}" "${BUILD_NUMBER}" --format simple-json | tee scan.json || true
          CRIT=$(jq '[.vulnerabilities[]? | select(.severity=="Critical")] | length' scan.json)
          HIGH=$(jq '[.vulnerabilities[]? | select(.severity=="High")] | length' scan.json)
          MED=$(jq  '[.vulnerabilities[]? | select(.severity=="Medium")] | length' scan.json)
          LOW=$(jq  '[.vulnerabilities[]? | select(.severity=="Low")]    | length' scan.json)
          {
            echo "### Xray Build Scan Results"
            echo "- **Build**: \`${BUILD_NAME}/${BUILD_NUMBER}\`"
            echo "- **Critical**: ${CRIT}"
            echo "- **High**: ${HIGH}"
            echo "- **Medium**: ${MED}"
            echo "- **Low**: ${LOW}"
          } >> "$GITHUB_STEP_SUMMARY"
