name: "JFrog OIDC CI Workflow with Curation + Xray (Docker + Python)"

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION || '3.11' }}
  BUILD_NAME:     ${{ vars.BUILD_NAME     || 'jfrog-docker-security-scan-build' }}
  BUILD_NUMBER:   ${{ vars.BUILD_NUMBER   || github.run_id }}

  # Registries / repos
  JF_REGISTRY:    ${{ vars.JF_REGISTRY    || 'aboavent.jfrog.io' }}        # host only
  DOCKER_REPO:    ${{ vars.DOCKER_REPO    || 'notes-api-docker-repo' }}    # Docker repo key in Artifactory
  CURATED_PYPI_VIRTUAL: ${{ vars.CURATED_PYPI_VIRTUAL || 'notes-api-pypi-curated' }}
  PYPI_LOCAL_REPO:      ${{ vars.PYPI_LOCAL_REPO      || 'notes-api-pypi-local' }}

  # Scanning / output
  FAIL_ON_SEVERITY: ${{ vars.FAIL_ON_SEVERITY || 'none' }}  # none|low|medium|high|critical
  XRAY_FORMAT: table

  # JFrog CLI quality-of-life
  JFROG_CLI_LOG_LEVEL: ERROR
  JFROG_CLI_OFFER_CONFIG: "false"

jobs:
  build-scan-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure jq is available
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y jq
          fi

      - name: Setup JFrog CLI (OIDC)
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}  # e.g., https://aboavent.jfrog.io
        with:
          oidc-provider-name: github-oidc-integration

      - name: "Sanity: show effective settings"
        shell: bash
        run: |
          set -euo pipefail
          echo "DOCKER_REPO=${{ env.DOCKER_REPO }}"
          jf rt curl -s -XGET "/api/repositories/${{ env.DOCKER_REPO }}" | jq '{key,packageType,type,repositories,defaultDeploymentRepo}'
          {
            echo "### JFrog Settings"
            echo "- **JF_URL**: \`${{ vars.JF_URL }}\`"
            echo "- **DOCKER_REPO**: \`${{ env.DOCKER_REPO }}\`"
          } >> "$GITHUB_STEP_SUMMARY"

      # ---------- Source scan: SAST / Secrets / IaC (non-blocking) ----------
      - name: Scan repository (non-blocking)
        run: jf scan . --fail=false --format "${{ env.XRAY_FORMAT }}"

      # ---------- Curation (pip) ----------
      - name: Configure pip to resolve via curated PyPI (project)
        shell: bash
        run: |
          set -euo pipefail
          jf pip-config \
            --repo-resolve "${{ env.CURATED_PYPI_VIRTUAL }}" \
            --server-id-resolve "setup-jfrog-cli-server"
          # show created config files
          find .jfrog -maxdepth 3 -type f -print || true

      - name: Curation audit (project)
        shell: bash
        run: jf curation-audit --format table || true

      # ---------- Build Python package (sdist + wheel) ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build Python dist
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip build
          python -m build
          ls -lh dist || true

      # ---------- Build Docker image ----------
      - name: Compose image tag
        id: tags
        shell: bash
        run: |
          NAME="notes-api"
          SAFE_BRANCH=$(echo "${GITHUB_REF_NAME:-main}" | tr '/ ' '--')
          REF_TAG="${{ env.JF_REGISTRY }}/${{ env.DOCKER_REPO }}/${NAME}:${SAFE_BRANCH}"
          echo "ref_tag=${REF_TAG}" >> "$GITHUB_OUTPUT"

      - name: Build image (local)
        run: |
          docker build -t "${{ steps.tags.outputs.ref_tag }}" .

      # ---------- Local image scan with Xray (non-blocking) ----------
      - name: Docker image scan (local daemon, non-blocking)
        shell: bash
        run: jf docker scan "${{ steps.tags.outputs.ref_tag }}" --fail=false --format "${{ env.XRAY_FORMAT }}"

      # ---------- Push & record build-info ----------
      - name: Push image & record build-info (ref tag)
        env:
          BUILD_NAME:   ${{ env.BUILD_NAME }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        shell: bash
        run: |
          jf rt docker-push "${{ steps.tags.outputs.ref_tag }}" "${{ env.DOCKER_REPO }}" \
            --build-name "${BUILD_NAME}" --build-number "${BUILD_NUMBER}"

      # ---------- Publish Python package to Artifactory (PyPI local) ----------
      - name: Upload Python dist to PyPI local (record build-info)
        if: ${{ always() }}  # don't block Docker path if Python build produced no dists
        env:
          BUILD_NAME:   ${{ env.BUILD_NAME }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        shell: bash
        run: |
          set -euo pipefail
          if compgen -G "dist/*" > /dev/null; then
            jf rt upload "dist/*" "${{ env.PYPI_LOCAL_REPO }}/" \
              --build-name "${BUILD_NAME}" --build-number "${BUILD_NUMBER}"
          else
            echo "No Python distributions found under dist/. Skipping upload."
          fi

      # ---------- Publish build-info ----------
      - name: Publish build-info
        env:
          BUILD_NAME:   ${{ env.BUILD_NAME }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        run: jf rt build-publish "${BUILD_NAME}" "${BUILD_NUMBER}"

      # ---------- Xray Build Scan (policy-gated) ----------
      - name: Scan published build (policy-gated)
        env:
          BUILD_NAME:       ${{ env.BUILD_NAME }}
          BUILD_NUMBER:     ${{ env.BUILD_NUMBER }}
          FAIL_ON_SEVERITY: ${{ env.FAIL_ON_SEVERITY }}
        shell: bash
        run: |
          if [ "${FAIL_ON_SEVERITY}" = "none" ]; then
            jf bs "${BUILD_NAME}" "${BUILD_NUMBER}" || true
          else
            jf bs "${BUILD_NAME}" "${BUILD_NUMBER}" --fail-on-severity "${FAIL_ON_SEVERITY}"
          fi

      - name: Summarize Xray build scan in job summary
        env:
          BUILD_NAME:   ${{ env.BUILD_NAME }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
        run: |
          set -euo pipefail
          jf bs "${BUILD_NAME}" "${BUILD_NUMBER}" --format simple-json | tee scan.json || true
          CRIT=$(jq '[.vulnerabilities[]? | select(.severity=="Critical")] | length' scan.json)
          HIGH=$(jq '[.vulnerabilities[]? | select(.severity=="High")] | length' scan.json)
          MED=$(jq  '[.vulnerabilities[]? | select(.severity=="Medium")] | length' scan.json)
          LOW=$(jq  '[.vulnerabilities[]? | select(.severity=="Low")]    | length' scan.json)
          {
            echo "### Xray Build Scan Results"
            echo "- **Build**: \`${BUILD_NAME}/${BUILD_NUMBER}\`"
            echo "- **Critical**: ${CRIT}"
            echo "- **High**: ${HIGH}"
            echo "- **Medium**: ${MED}"
            echo "- **Low**: ${LOW}"
          } >> "$GITHUB_STEP_SUMMARY"
